import { OcButton } from "./client-side/oc-button/oc-button.js";
import { OcList } from "./client-side/oc-list/oc-list.js";
import { OcQuote } from "./client-side/oc-quote/oc-quote.js";
import { OcTextInput } from "./client-side/oc-text-input/oc-text-input.js";
import { OcTextinput } from "./client-side/oc-textinput/oc-textinput.js";
import { OcTextInputLight } from "./client-side/oc-text-input-light/oc-text-input-light.js";
import { OcButtonServer } from "./server/oc-button-server/oc-button-server.js";
import { OcTextinputServer } from "./server/oc-textinput-server/oc-textinput-server.js";
import { OcButtonServerHybrid } from "./server/oc-button-server-hybrid/oc-button-server-hybrid.js";
import { OcInputExtend } from "./client-side/oc-input-extend/oc-input-extend.js";
import { OcPage } from "./client-side/oc-page/oc-page.js";
import { OcPopover } from "./client-side/oc-popover/oc-popover.js";
import { OcTable } from "./client-side/oc-table/oc-table.js";
import { OcDataStarwars } from "./client-side/oc-data-starwars/oc-data-starwars.js";
import { OcTableStarwars } from "./client-side/oc-table-starwars/oc-table-starwars.js";

customElements.define("oc-button", OcButton);
customElements.define("oc-list", OcList);
customElements.define("oc-quote", OcQuote);
customElements.define("oc-text-input", OcTextInput);
customElements.define("oc-textinput", OcTextinput);
customElements.define("oc-text-input-light", OcTextInputLight);
customElements.define("oc-button-server", OcButtonServer);
customElements.define("oc-textinput-server", OcTextinputServer);
customElements.define("oc-button-server-hybrid", OcButtonServerHybrid);
customElements.define("oc-input-extend", OcInputExtend, { extends: "input" });
customElements.define("oc-page", OcPage);
customElements.define("oc-popover", OcPopover);
customElements.define("oc-table", OcTable);
customElements.define("oc-table-starwars", OcTableStarwars);
customElements.define("oc-data-starwars", OcDataStarwars);